#!/usr/bin/bash

while true
do
 battery="$( acpi -b | grep -P -o '[0-9]+(?=%)' )"
 charging="$( acpi -b | grep -P -o 'Charging|Discharging' )"

 if [[ $charging=="Discharging" ]]
 then
 	if [[ ($battery -le 20) ]]
    then
        if [[ $battery -le 10 ]]
        then
            notify-send -u critical "Battery Critical"
            sleep 30s
        else
            notify-send -u normal "Battery Low"
            sleep 30s
        fi
    fi
 fi

 if  [[ $charging=="Charging" ]] && [[ $battery -ge 80 ]]
 then
     notify-send -u normal "Disconnect Charger"
     sleep 30s
 fi

 sleep 5s
done
