#!/usr/bin/env zsh

cd ~

# sudo pacman -Syu
sudo pacman -S --needed \
zsh \
zsh-autosuggestions \
zsh-syntax-highlighting \
zsh-history-substring-search \
alacritty \
byobu \
vifm \
exa \
zoxide \
duf \
emacs \
neovim \
mpv \
yt-dlp \
youtube-dl \
aria2 \
mpd \
ncmpcpp \
sxiv \
feh \
gthumb \
zathura \
zathura-pdf-mupdf \
cmus \
qutebrowser \
brave-browser \
aria2 \
atool \
btop \
bat \
syncthing \
unison \
stow \
gcc \
ttf-jetbrains-mono \
starship \
yay \
rofi \
figlet \
neofetch \
gcc \
make \
cmake \
automake \
pkgconf

sudo yay -S --needed \
    nsxiv \
    neo-matrix \
    ytfzf \
    toilet \
    dijo-bin \
    neo-matrix-git \
    dragon-drag-and-drop
