#!/usr/bin/env zsh

# uses jpegoptim, only works on jpegs

[[ -z "$1" ]] && echo "Usage: pdfer [filename] [quality 1-100] [filter 1-100]" && exit 0 
[[ -z "$2" ]] && jpegQuality="30" || jpegQuality="$2"
[[ -z "$3" ]] && textcleanerIntensity="40" || textcleanerIntensity="$3"

filename="$1"
files=()

for file in * 
do
  mimetype=$( file -b --mime-type "$file" )
  [[ $mimetype == image/* ]] && files+=( "$file" )
done

mkdir -p originals
cp "${files[@]}" originals

jpegoptim -q -m "$jpegQuality" "${files[@]}"

for file in "${files[@]}"
do
  textcleaner -f "$textcleanerIntensity" "$file" "$file"
done

img2pdf -S A4 --auto-orient --output "$filename" "${files[@]}"

rm "${files[@]}"


