#!/usr/bin/env zsh

# Possible to use FILE instead of exiftool

files=(?(*.jpg|*.gif|*.png|*.jpeg))
sizes=( $( exiftool -S -T -ImageSize ?(*.jpg|*.gif|*.png|*.jpeg) ) )
phone=()
desktop=()
arraylength=${#files[@]}

testRatio() {

}

for (( i=0; i<${arraylength}; i++ ));
do
  size=$sizes[$i]
  ratio=$( echo "scale=2; ${size#*x} / ${size%x*}" | bc )
  if [[ $ratio -gt 1.2 ]]
  then
    phone+=( "$files[i]" )
  elif [[ $ratio -lt 0.8 ]]
  then
    desktop+=( "$files[i]" )
  fi
done

echo $phone
echo $desktop

